### ISSUE TITLE
ERROR: 300 Multiple Choices trying to unload bundle when multiple configs loaded.

### ISSUE THREAD

**Issue by edwardcallahan** [typesafehub/conductr-cli#43] opened 2015-04-06 17:45 UTC
With the same app bundle loaded, one with an aux config bundle and one without (default config), it is not possible to unload the non-config'd bundle first.

``` bash
ubuntu@10:~$ conduct info
ID               NAME         #REP  #STR  #RUN
d248907          visualizer      3     0     1
353a913          project-doc     3     0     0
353a913-bbb42aa  project-doc     3     0     1

ubuntu@10:~$ conduct unload project-doc
ERROR: 300 Multiple Choices
ERROR: Specified Bundle ID/name: 'project-doc' resulted in multiple Bundle IDs: '353a913dd1dc24582139162b07d451c9, 353a913dd1dc24582139162b07d451c9-bbb42aacf1306626ce4ec53768b7016a'

ubuntu@10:~$ conduct unload 353a913dd1dc24582139162b07d451c9
ERROR: 300 Multiple Choices
ERROR: Specified Bundle ID/name: '353a913dd1dc24582139162b07d451c9' resulted in multiple Bundle IDs: '353a913dd1dc24582139162b07d451c9, 353a913dd1dc24582139162b07d451c9-bbb42aacf1306626ce4ec53768b7016a'

ubuntu@10:~$ conduct version
0.12
```

Only after stopping and unloading 353a913-bbb42aa is it possible to unload 353a913.

**Comment by huntc** [comment] 2015-04-06 21:06
In this instance you need to specify the Id given the ambiguity. Does that need spelling out in the doc?

Closing as not a bug.

**Comment by edwardcallahan** [comment] 2015-04-06 21:19
Unloading by bundle does not work either; 353a913 nor 353a913dd1dc24582139162b07d451c9

``` bash
ubuntu@10:~$ conduct unload 353a913dd1dc24582139162b07d451c9
ERROR: 300 Multiple Choices
ERROR: Specified Bundle ID/name: '353a913dd1dc24582139162b07d451c9' resulted in multiple Bundle IDs: '353a913dd1dc24582139162b07d451c9, 353a913dd1dc24582139162b07d451c9-bbb42aacf1306626ce4ec53768b7016a'
```

**Comment by huntc** [comment] 2015-04-06 21:29
Oh, yes, bug. Thanks

**Comment by huntc** [comment] 2015-04-06 21:30
@2m any ideas? I thought we had repaired this scenario a while back... :-)

**Comment by huntc** [comment] 2015-04-06 21:58
In the instance where a full bundle id is expressed then there should be a match, even if the id is half the id of something else.

**Comment by huntc** [comment] 2015-04-07 06:05
I've just delved into the code. If you specify the full 64 character hash then it will disambiguite in this scenario. Perhaps the fix is to enhance the error message.

**Comment by huntc** [comment] 2015-04-07 06:52
Fixed by https://github.com/typesafehub/typesafe-conductr/pull/558

Closing here.

**Closed as completed by huntc** 2015-04-07 06:52 UTC
