### ISSUE TITLE
Visualizer unreachable when using externally exposed port (9999) in sandbox with haproxy

### ISSUE THREAD

**Issue by kikiya** [typesafehub/conductr-cli#289] opened 2017-02-01 04:40 UTC
- Upgraded to CLI 1.0.1
- Ran ```sandbox run 2.0.0```
- deployed visualizer by running ```conduct load visualizer```
- started visualizer by running ```conduct run visualizer```
- tried reaching visualizer from browser at address ```192.168.10.1:9999``` and got an error saying ```cannot connect to server```
-  used the service locator address ```192.168.10.1:9008/service/visualizer``` and it was able to resolve to the internal address. However exposed port is not working. 

Tried ```conduct stop/start``` haproxy bundle
Tried ```docker restart``` on haproxy container
Neither resolved the issue.

**Comment by fsat** [comment] 2017-02-01 23:20
@kikiya - would you be able to paste the output from these commands please? 
* `sandbox run 2.0.0`
* `conduct load visualizer`
* `conduct run visualizer`

Could you retry accessing `192.168.10.1:9008/services/visualizer` please? Note it's `services` with `s` at the end instead of `service`. You should be redirected to the actual Visualizer service. ConductR 2 sandbox no longer runs within Docker container, so the Visualizer port should be exposed without additional options.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ curl -v 192.168.10.1:9008/services/visualizer
*   Trying 192.168.10.1...
* Connected to 192.168.10.1 (192.168.10.1) port 9008 (#0)
> GET /services/visualizer HTTP/1.1
> Host: 192.168.10.1:9008
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
< Location: http://192.168.10.1:10917
< Cache-Control: private="Location", max-age=60
< Server: akka-http/10.0.0
< Date: Wed, 01 Feb 2017 23:06:53 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 36
<
* Connection #0 to host 192.168.10.1 left intact
Located at http://192.168.10.1:10917
```

Next, I'd also like to confirm if ConductR HAProxy is working with the HAProxy container. Note that HAProxy is running within a docker container, so we need to expose the ports accessible from the host machine to the container.

With docker running, can you try `sandbox run 2.0.0 -f visualization`, and then access `192.168.10.1:9999` please?

If that is indeed failing, can you run `docker ps -a` and show the output please?

The HAProxy container should be called `sandbox-haproxy`, and when `sandbox run 2.0.0` is called only port `80`, `443`, and `9000` is exposed from the proxy (note the `PORTS` column).

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                             NAMES
5bcddcf5cdbd        haproxy:1.5         "/docker-entrypoin..."   29 seconds ago      Up 27 seconds       192.168.10.1:80->80/tcp, 192.168.10.1:443->443/tcp, 192.168.10.1:9000->9000/tcp   sandbox-haproxy
```

If you run `sandbox run 2.0.0 -f visualization`, the visualization feature requires port `9999` to be opened so the sandbox will restart the HAProxy container with additional port `9999` exposed. Note additional port mapping for `9999` in the `PORTS` column.

```
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                                                                                          NAMES
dadb0aa6c908        haproxy:1.5         "/docker-entrypoin..."   About a minute ago   Up About a minute   192.168.10.1:80->80/tcp, 192.168.10.1:443->443/tcp, 192.168.10.1:9000->9000/tcp, 192.168.10.1:9999->9999/tcp   sandbox-haproxy
```

**Comment by markusjura** [comment] 2017-02-02 00:06
@fsat Kiki and me were sitting together when she found the issue. I was also able to reproduce the issue. Some additional info:
- The service locator 192.168.10.1:9008/service/visualizer was working fine
- Starting the visualizer as a feature is also working fine. `sandbox run 2.0.0 -f visualization`. The visualizer is then accessible on port 9999
- However, when starting the sandbox incl. HAProxy without the visualization feature and afterwards deploying the visualizer with `conduct load` and `conduct run`, the visualizer is not accessible on port 9999. The visualizer is though available through the service locator

**Comment by fsat** [comment] 2017-02-02 00:47
@markusjura - ah, I see. That's because the HAProxy runs within the docker container, and it doesn't have port `9999` exposed by default when started with `sandbox run 2.0.0`.

At the moment HAProxy just opens `80`, `443`, and `9000` by default.

Perhaps we should just open all the feature ports when starting the HAProxy like `3000`, `5601`, `9200` and `9999` regardless whether the feature is enabled. With this, the proxy will already be accessible when the feature is loaded and run later after `sandbox run`.

Wdyt?

**Comment by huntc** [comment] 2017-02-02 23:23
@fsat @markusjura and I discussed yesterday that perhaps we should just open all ports > 1024 excluding the 9005-9010 and 19005-19010 ranges. I think this should work.

**Comment by fsat** [comment] 2017-02-03 04:23
@huntc - unfortunately this won't work as each port mapped will consume one connection.

I've tried opening port `1025` to `2000` and failed with too many connections error.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ docker run -d --name sandbox-haproxy -p 192.168.10.1:1025-2000:1025-2000 -v /Users/felixsatyaputra/.conductr/proxy/haproxy:/usr/local/etc/haproxy:ro haproxy:1.5
0ab262dc89409412cad601c634ec747e84422612ee59db58dc29f86a85c2bc29
docker: Error response from daemon: driver failed programming external connectivity on endpoint sandbox-haproxy (c10c93d8d5dafca49f9c5729d55e129130e812a94c39f98fe08d3648f2274197): Error starting userland proxy: Bind for 192.168.10.1:1108: unexpected error Hostnet.Host_uwt.Sockets.Too_many_connections.
```

**Comment by huntc** [comment] 2017-02-03 08:00
Ah ok - I wasn't sure how Docker implemented it. Thanks.

**Comment by markusjura** [comment] 2017-02-07 13:23
Fixed by https://github.com/typesafehub/conductr-cli/pull/296

**Closed as completed by markusjura** 2017-02-07 13:23 UTC
