### ISSUE TITLE
Retrieve conductr core and agent logs

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-cli#143] opened 2016-08-09 07:35 UTC
It would be nice to retrieve logs from ConductR core and agent from the CLI. Possible commands could be:

```
conduct logs conductr
conduct logs conductr-agent
```

**Comment by huntc** [comment] 2016-11-26 04:33
Closing as a duplicate of #121

**Closed as completed by huntc** 2016-11-26 04:33 UTC
