### ISSUE TITLE
Times out when resources unavailable

### ISSUE THREAD

**Issue by bayarmunkh** [typesafehub/conductr-cli#384] opened 2017-03-31 15:52 UTC
When scaling a bundle fails due to no resources available, `conduct` cli waits forever and times out.

I think appropriate  behavior would be fail fast, then report the error to the user.

**Comment by huntc** [comment] 2017-03-31 23:19
Thanks for this. Closing given that it is a duplicate of https://github.com/typesafehub/conductr-cli/issues/316

**Closed as completed by huntc** 2017-03-31 23:19 UTC

**Comment by typesafe-tools** [comment] 2017-05-11 00:26
![](https://github.trello.services/images/mini-trello-icon.png) [Improve "conduct run" exiting](https://trello.com/c/F9oVvq3g/669-improve-conduct-run-exiting)
